from typing import TypedDict
from langgraph.graph import StateGraph, END
from groq import Groq
from app.core.config import settings
from langfuse import observe

client = Groq(api_key=settings.groq_api_key)

class GuardrailState(TypedDict):
    roadmap: str
    risk_level: str
    reasoning: str

@observe()
def check_hallucination_risk(state: GuardrailState) -> GuardrailState:
    prompt = f"""You are a strict fact-checker reviewing a career roadmap
generated by another AI. Look for vague, made-up, or overly confident claims
that aren't grounded in reality (e.g. fake course names, made-up statistics,
unrealistic timelines).

Respond in this exact format:
Risk Level: [Low/Medium/High]
Reasoning: [1-2 sentences explaining why]

Roadmap to review:
{state['roadmap']}
"""
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        max_tokens=200,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )
    output = response.choices[0].message.content
    return {"roadmap": state["roadmap"], "risk_level": "", "reasoning": output}

graph = StateGraph(GuardrailState)
graph.add_node("check", check_hallucination_risk)
graph.set_entry_point("check")
graph.add_edge("check", END)

guardrail_graph = graph.compile()