spring.application.name=backend
server.port=8080

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/nextstep_db?options=-c%20TimeZone=UTC
spring.datasource.username=shruti
spring.datasource.password=8125
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=INFO

jwt.secret=replace-this-with-a-long-random-base64-secret-key-later
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

admin.seed.email=admin@nextstep.ai
admin.seed.password=ChangeMe123